Repository ClobberXD/gunslinger, pull requests merged in 2019-03, with the labels that each got.

#10 Make bullets punch() instead of set_hp()
  api.lua
Labels: Action / change needed, Feature

#9 Fix non automatic guns not firing more than once
  api.lua
Labels: Bugfix

#18 Set up repository for Travis-CI integration
  .luacheck.rc
  .travis.yml
Labels: Action / change needed, Maintenance

#13 Use deferred raycasting to mimic behavior of projectile entity
  api.lua
Labels: @ Mechanics, Feature
